//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudnetManagement.LoginPageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginPageService.ILoginPageService")]
    public interface ILoginPageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginPageService/GetUserData", ReplyAction="http://tempuri.org/ILoginPageService/GetUserDataResponse")]
        StudentManagement_Service.StudentData.StudentData GetUserData(StudentManagement_Service.StudentData.StudentData studentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginPageService/GetUserData", ReplyAction="http://tempuri.org/ILoginPageService/GetUserDataResponse")]
        System.Threading.Tasks.Task<StudentManagement_Service.StudentData.StudentData> GetUserDataAsync(StudentManagement_Service.StudentData.StudentData studentData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginPageServiceChannel : StudnetManagement.LoginPageService.ILoginPageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginPageServiceClient : System.ServiceModel.ClientBase<StudnetManagement.LoginPageService.ILoginPageService>, StudnetManagement.LoginPageService.ILoginPageService {
        
        public LoginPageServiceClient() {
        }
        
        public LoginPageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginPageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginPageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginPageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentManagement_Service.StudentData.StudentData GetUserData(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.GetUserData(studentData);
        }
        
        public System.Threading.Tasks.Task<StudentManagement_Service.StudentData.StudentData> GetUserDataAsync(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.GetUserDataAsync(studentData);
        }
    }
}
