//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminDashboard_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminDashboard_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminDashboard_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptBtnTbl {
            get {
                return ResourceManager.GetString("AcceptBtnTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Buttons.
        /// </summary>
        internal static string ActiontblHead {
            get {
                return ResourceManager.GetString("ActiontblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Course.
        /// </summary>
        internal static string AddCourseBtn {
            get {
                return ResourceManager.GetString("AddCourseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        internal static string AdminDashboardPageHeading {
            get {
                return ResourceManager.GetString("AdminDashboardPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClasstblHead {
            get {
                return ResourceManager.GetString("ClasstblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID.
        /// </summary>
        internal static string CourseIdtblHead {
            get {
                return ResourceManager.GetString("CourseIdtblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string CourseNametblHead {
            get {
                return ResourceManager.GetString("CourseNametblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtnTbl {
            get {
                return ResourceManager.GetString("DeleteBtnTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteCourseBtnTbl {
            get {
                return ResourceManager.GetString("DeleteCourseBtnTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Course.
        /// </summary>
        internal static string DeleteCoursetblHead {
            get {
                return ResourceManager.GetString("DeleteCoursetblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        internal static string EmailIdtblHead {
            get {
                return ResourceManager.GetString("EmailIdtblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GendertblHead {
            get {
                return ResourceManager.GetString("GendertblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Courses.
        /// </summary>
        internal static string ManageCoursesbtn {
            get {
                return ResourceManager.GetString("ManageCoursesbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextBtn {
            get {
                return ResourceManager.GetString("NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousBtn {
            get {
                return ResourceManager.GetString("PreviousBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string RejectBtnTbl {
            get {
                return ResourceManager.GetString("RejectBtnTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatustblHead {
            get {
                return ResourceManager.GetString("StatustblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        internal static string StudentIdtblHead {
            get {
                return ResourceManager.GetString("StudentIdtblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string StudentNametblHead {
            get {
                return ResourceManager.GetString("StudentNametblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewBtnTbl {
            get {
                return ResourceManager.GetString("ViewBtnTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Courses.
        /// </summary>
        internal static string ViewCoursesBtn {
            get {
                return ResourceManager.GetString("ViewCoursesBtn", resourceCulture);
            }
        }
    }
}
