//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudentRegistration_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentRegistration_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StudentRegistration_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class :.
        /// </summary>
        internal static string Classlbl {
            get {
                return ResourceManager.GetString("Classlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses :.
        /// </summary>
        internal static string Courseslbl {
            get {
                return ResourceManager.GetString("Courseslbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID :.
        /// </summary>
        internal static string EmailIDlbl {
            get {
                return ResourceManager.GetString("EmailIDlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FemaleGenderlbl {
            get {
                return ResourceManager.GetString("FemaleGenderlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname :.
        /// </summary>
        internal static string FullNamelbl {
            get {
                return ResourceManager.GetString("FullNamelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender :.
        /// </summary>
        internal static string Genderlbl {
            get {
                return ResourceManager.GetString("Genderlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MaleGenderlbl {
            get {
                return ResourceManager.GetString("MaleGenderlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string OthersGenderlbl {
            get {
                return ResourceManager.GetString("OthersGenderlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string Passwordlbl {
            get {
                return ResourceManager.GetString("Passwordlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number :.
        /// </summary>
        internal static string PhoneNumberlbl {
            get {
                return ResourceManager.GetString("PhoneNumberlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registration Page.
        /// </summary>
        internal static string StudentRegistrationPageHeading {
            get {
                return ResourceManager.GetString("StudentRegistrationPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submitbtn {
            get {
                return ResourceManager.GetString("Submitbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string Usernamelbl {
            get {
                return ResourceManager.GetString("Usernamelbl", resourceCulture);
            }
        }
    }
}
