//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudnetManagement.StudentProfileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentProfileService.IStudentProfileService")]
    public interface IStudentProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfileService/GetStudentData", ReplyAction="http://tempuri.org/IStudentProfileService/GetStudentDataResponse")]
        StudentManagement_Service.StudentData.StudentData GetStudentData(StudentManagement_Service.StudentData.StudentData studentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfileService/GetStudentData", ReplyAction="http://tempuri.org/IStudentProfileService/GetStudentDataResponse")]
        System.Threading.Tasks.Task<StudentManagement_Service.StudentData.StudentData> GetStudentDataAsync(StudentManagement_Service.StudentData.StudentData studentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfileService/GetSelectedCourses", ReplyAction="http://tempuri.org/IStudentProfileService/GetSelectedCoursesResponse")]
        int[] GetSelectedCourses(StudentManagement_Service.StudentData.StudentData studentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfileService/GetSelectedCourses", ReplyAction="http://tempuri.org/IStudentProfileService/GetSelectedCoursesResponse")]
        System.Threading.Tasks.Task<int[]> GetSelectedCoursesAsync(StudentManagement_Service.StudentData.StudentData studentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfileService/UpdateStudentData", ReplyAction="http://tempuri.org/IStudentProfileService/UpdateStudentDataResponse")]
        bool UpdateStudentData(StudentManagement_Service.StudentData.StudentData studentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfileService/UpdateStudentData", ReplyAction="http://tempuri.org/IStudentProfileService/UpdateStudentDataResponse")]
        System.Threading.Tasks.Task<bool> UpdateStudentDataAsync(StudentManagement_Service.StudentData.StudentData studentData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentProfileServiceChannel : StudnetManagement.StudentProfileService.IStudentProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentProfileServiceClient : System.ServiceModel.ClientBase<StudnetManagement.StudentProfileService.IStudentProfileService>, StudnetManagement.StudentProfileService.IStudentProfileService {
        
        public StudentProfileServiceClient() {
        }
        
        public StudentProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentManagement_Service.StudentData.StudentData GetStudentData(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.GetStudentData(studentData);
        }
        
        public System.Threading.Tasks.Task<StudentManagement_Service.StudentData.StudentData> GetStudentDataAsync(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.GetStudentDataAsync(studentData);
        }
        
        public int[] GetSelectedCourses(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.GetSelectedCourses(studentData);
        }
        
        public System.Threading.Tasks.Task<int[]> GetSelectedCoursesAsync(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.GetSelectedCoursesAsync(studentData);
        }
        
        public bool UpdateStudentData(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.UpdateStudentData(studentData);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStudentDataAsync(StudentManagement_Service.StudentData.StudentData studentData) {
            return base.Channel.UpdateStudentDataAsync(studentData);
        }
    }
}
